{% set name = "fluidfft-builder" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fluidfft_builder-{{ version }}.tar.gz
  sha256: c0af9ceca27ae3a00ccf2f160703be9e394d8b886b8a02653b6c0a12a4f54a90

build:
  entry_points:
    - fluidfft-builder-make-file = fluidfft_builder.make_cy_files:main
    - fluidfft-builder-print-include-dir = fluidfft_builder:print_include_dir
    - fluidfft-builder-print-include-dir-cython = fluidfft_builder:print_include_dir_cython
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - fluidfft_builder
  commands:
    - pip check
    # cannot be tested here...
    # - fluidfft-builder-make-file --help
    - fluidfft-builder-print-include-dir
    - fluidfft-builder-print-include-dir-cython
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Fluidfft plugin dependencies
  license: MIT
  license_file: LICENSE
  home: https://fluidfft.readthedocs.io

extra:
  recipe-maintainers:
    - paugier
